In [2]:
import numpy as np
import pandas as pd
from numpy import linalg as la

1. Create 5 matrices with five different dimensions (1-D,2-D,...5-D)


In [3]:
a=np.array([[1,2]])
b=np.array([[1,2],[3,4]])
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
d=np.array([[1,2,3,4],[5,6,2,7],[5,56,636,1],[64,6,32,76,12]])
e=np.array([[1,2,3,5],[56,6,3,2],[3,56,786,23],[86,342,123,75],[45,23,87,56]])
print(a)
print(b)
print(c)
print(d)
print(e)

[[1 2]]
[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[list([1, 2, 3, 4]) list([5, 6, 2, 7]) list([5, 56, 636, 1])
 list([64, 6, 32, 76, 12])]
[[  1   2   3   5]
 [ 56   6   3   2]
 [  3  56 786  23]
 [ 86 342 123  75]
 [ 45  23  87  56]]


<ipython-input-3-23ea29a4fd19>:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  d=np.array([[1,2,3,4],[5,6,2,7],[5,56,636,1],[64,6,32,76,12]])


2. Find determinants of 5 matrices and display your output

In [3]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.array([[65,34],[76,97]])
d=np.array([[54,76,98],[32,13,65],[65,78,53]])
e=np.array([[565,788],[351,545]])
print(la.det(a))
print(la.det(b))
print(la.det(c))
print(la.det(d))
print(la.det(e))

-2.0000000000000004
-9.51619735392994e-16
3721.000000000001
117427.99999999981
31336.999999999975


3. Find inverse of the above 5 matrices and display your output

In [5]:
print("1st Array:",la.inv(a))
print("2nd Array:",la.inv(b))
print("3rd Array:",la.inv(c))
print("4th Array:",la.inv(d))
print("5th Array:",la.inv(e))


1st Array: [[-2.   1. ]
 [ 1.5 -0.5]]
2nd Array: [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
3rd Array: [[ 0.02606826 -0.00913733]
 [-0.02042462  0.01746842]]
4th Array: [[-0.03730797  0.03079334  0.03121913]
 [ 0.0215366  -0.02987362 -0.00318493]
 [ 0.01405968  0.00619954 -0.01473243]]
5th Array: [[ 0.01739158 -0.02514599]
 [-0.01120082  0.01802981]]


4. Find the rank, diagonal and trace of the 5 matrices

In [12]:
print("A:")
print(la.matrix_rank(a))
print(np.diag(a))
print(np.trace(a))
print("B:")
print(la.matrix_rank(b))
print(np.diag(b))
print(np.trace(b))
print("C:")
print(la.matrix_rank(c))
print(np.diag(c))
print(np.trace(c))
print("D:")
print(la.matrix_rank(d))
print(np.diag(d))
print(np.trace(d))
print("E:")
print(la.matrix_rank(e))
print(np.diag(e))
print(np.trace(e))

A:
2
[1 4]
5
B:
2
[1 5 9]
15
C:
2
[65 97]
162
D:
3
[54 13 53]
120
E:
2
[565 545]
1110


5. Find Eigen value and eigen vector for 5 matrices

In [17]:
print("A:")
print(la.eigvals(a))
print(la.eig(a))
print("B:")
print(la.eigvals(b))
print(la.eig(b))
print("C:")
print(la.eigvals(c))
print(la.eig(c))
print("D:")
print(la.eigvals(c))
print(la.eig(c))
print("E:")
print(la.eigvals(e))
print(la.eig(e))

A:
[-0.37228132  5.37228132]
(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
B:
[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
(array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))
C:
[ 27.70834962 134.29165038]
(array([ 27.70834962, 134.29165038]), array([[-0.67374076, -0.44050717],
       [ 0.73896779, -0.89774909]]))
D:
[ 27.70834962 134.29165038]
(array([ 27.70834962, 134.29165038]), array([[-0.67374076, -0.44050717],
       [ 0.73896779, -0.89774909]]))
E:
[1081.01140672   28.98859328]
(array([1081.01140672,   28.98859328]), array([[ 0.83658981, -0.82684286],
       [ 0.5478298 ,  0.562433  ]]))
